# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lYAPdG3brvm1c40yZl4OMh0zUJReHfq

DESAFIO N° 44: Las Estructuras de Datos Base (Bloque 1)
Define primero los moldes o atributos de cada entidad individual.
"""

class Libro:
    def __init__(self, id: str, titulo: str, disponible: bool):
        self.id = id
        self.titulo = titulo
        self.disponible = disponible

class Usuario:
    def __init__(self, id: str, nombre: str, activo: bool):
        self.id = id
        self.nombre = nombre
        self.activo = activo

class Multa:
    def __init__(self, id: str, idUsuario: str, monto: float, pagada: bool):
        self.id = id
        self.idUsuario = idUsuario
        self.monto = monto
        self.pagada = pagada

class Prestamo:
    def __init__(self, id: str, idLibro: str, idUsuario: str, fechaPrestamo: str, fechaLimite: str, devuelto: bool):
        self.id = id
        self.idLibro = idLibro
        self.idUsuario = idUsuario
        self.fechaPrestamo = fechaPrestamo # Consider using datetime objects for dates
        self.fechaLimite = fechaLimite     # Consider using datetime objects for dates
        self.devuelto = devuelto

"""El TAD Contenedor / Fachada (Bloques 2 y 3 juntos)
Define la estructura central (TAD_Biblioteca) e implementa la función realizarPrestamo dentro de ella.
"""

from datetime import datetime, timedelta
import uuid # For generating unique IDs

class Biblioteca:
    def __init__(self):
        # Atributos Privados
        self._coleccionLibros = []      # Lista de Libro
        self._coleccionUsuarios = []    # Lista de Usuario
        self._coleccionPrestamos = []   # Lista de Prestamo
        self._coleccionMultas = []      # Lista de Multa

    # Helper method to find a user by ID
    def _buscarUsuarioPorId(self, idUsuario: str):
        for usuario in self._coleccionUsuarios:
            if usuario.id == idUsuario:
                return usuario
        return None

    # Helper method to find a book by ID
    def _buscarLibroPorId(self, idLibro: str):
        for libro in self._coleccionLibros:
            if libro.id == idLibro:
                return libro
        return None

    # Operación Pública: verificar multas pendientes
    def _usuarioTieneMultasPendientes(self, idUsuario: str) -> bool:
        for multa in self._coleccionMultas:
            if multa.idUsuario == idUsuario and not multa.pagada:
                return True
        return False

    # Operación Pública: realizarPrestamo
    def realizarPrestamo(self, idUsuario: str, idLibro: str, fechaActual_str: str) -> bool:
        try:
            fechaActual = datetime.strptime(fechaActual_str, "%Y-%m-%d") # Assuming YYYY-MM-DD format
        except ValueError:
            print("Error: Formato de fecha actual inválido. Use YYYY-MM-DD.")
            return False

        # 1. Validar Usuario
        usuario = self._buscarUsuarioPorId(idUsuario)
        if usuario is None or not usuario.activo:
            print("Error: El usuario no existe o se encuentra inactivo.")
            return False

        # 2. Validar Libro
        libro = self._buscarLibroPorId(idLibro)
        if libro is None or not libro.disponible:
            print("Error: El libro no existe o ya se encuentra prestado.")
            return False

        # 3. Validar Multas
        if self._usuarioTieneMultasPendientes(idUsuario):
            print("Error: El usuario tiene multas pendientes por pagar.")
            return False

        # 4. Crear Préstamo y actualizar estados
        libro.disponible = False

        # Generar un nuevo ID único para el préstamo
        nuevo_prestamo_id = str(uuid.uuid4())

        # Calcular la fecha límite (14 días después de la fecha actual)
        fechaLimite = fechaActual + timedelta(days=14)

        nuevoPrestamo = Prestamo(
            id = nuevo_prestamo_id,
            idLibro = idLibro,
            idUsuario = idUsuario,
            fechaPrestamo = fechaActual.strftime("%Y-%m-%d"), # Guardar como string
            fechaLimite = fechaLimite.strftime("%Y-%m-%d"),   # Guardar como string
            devuelto = False
        )

        self._coleccionPrestamos.append(nuevoPrestamo)
        print(f"Préstamo realizado exitosamente para el libro {idLibro} y usuario {idUsuario}.")
        return True

    # Métodos para añadir elementos (útiles para pruebas)
    def add_libro(self, libro: Libro):
        self._coleccionLibros.append(libro)

    def add_usuario(self, usuario: Usuario):
        self._coleccionUsuarios.append(usuario)

    def add_multa(self, multa: Multa):
        self._coleccionMultas.append(multa)

    # Métodos para obtener colecciones (útiles para depuración y pruebas)
    def get_libros(self):
        return self._coleccionLibros

    def get_usuarios(self):
        return self._coleccionUsuarios

    def get_prestamos(self):
        return self._coleccionPrestamos

    def get_multas(self):
        return self._coleccionMultas

"""DESAFIO N° 45. Para resolver este desafío en programación de videojuegos, la solución estándar en la industria es evolucionar desde TADs estáticos hacia patrones de diseño flexibles o una Arquitectura Orientada a Componentes (ECS / Composition over Inheritance)."""

from abc import ABC, abstractmethod

# Placeholder functions for demonstration
def dañar(objetivo, cantidad):
    print(f"{objetivo} recibe {cantidad} puntos de daño.")

def consumirMana(origen, cantidad):
    print(f"{origen} consume {cantidad} puntos de maná.")

# Interfaz Habilidad (Abstract Base Class)
class Habilidad(ABC):
    @abstractmethod
    def ejecutar(self, origen, objetivo):
        pass

# TAD AtaqueEspada Implementa Habilidad
class AtaqueEspada(Habilidad):
    def ejecutar(self, origen, objetivo):
        print(f"{origen} realiza un ataque con espada a {objetivo}.")
        dañar(objetivo, 15)

# TAD DisparoMagico Implementa Habilidad
class DisparoMagico(Habilidad):
    def ejecutar(self, origen, objetivo):
        print(f"{origen} lanza un disparo mágico a {objetivo}.")
        dañar(objetivo, 25)
        consumirMana(origen, 10)

"""Interfaz de Habilidad (Patrón Estrategia)"""

class Personaje:
    def __init__(self, id: str, vida: int):
        self.id = id
        self.vida = vida
        self.habilidadEquipada: Habilidad = None  # Referencia dinámica a cualquier habilidad

    def equipar_habilidad(self, nueva_habilidad: Habilidad):
        self.habilidadEquipada = nueva_habilidad
        print(f"{self.id} ha equipado la habilidad {type(nueva_habilidad).__name__}.")

    def realizar_accion(self, objetivo):
        if self.habilidadEquipada is not None:
            print(f"{self.id} usa {type(self.habilidadEquipada).__name__} contra {objetivo.id}.")
            self.habilidadEquipada.ejecutar(self.id, objetivo.id)
        else:
            print(f"{self.id} no tiene ninguna habilidad equipada para realizar una acción.")

"""TAD Personaje Decoupled (Contenedor)

DESAFIO N°46: El problema principal de gestionar un inventario de cadena minorista mediante TADs anidados (por ejemplo, que el TAD_Tienda contenga directamente una lista de TAD_Producto, una lista de TAD_Empleado y sus TAD_Transaccion) es que genera duplicación de datos, alto consumo de memoria y problemas de consistencia.

Entidades Base (Sin anidamiento masivo)
"""

class Producto:
    def __init__(self, idProducto: str, nombre: str, precioBase: float):
        self.idProducto = idProducto
        self.nombre = nombre
        self.precioBase = precioBase

class Empleado:
    def __init__(self, idEmpleado: str, idTienda: str, nombre: str):
        self.idEmpleado = idEmpleado
        self.idTienda = idTienda  # Foreign Key (belonging)
        self.nombre = nombre

class Tienda:
    def __init__(self, idTienda: str, direccion: str):
        self.idTienda = idTienda
        self.direccion = direccion

"""Entidades Relacionales Intermedias"""

from datetime import datetime

# Modela la relación Muchos-a-Muchos entre Tiendas y Productos
class InventarioItem:
    def __init__(self, idTienda: str, idProducto: str, stockActual: int, stockMinimo: int):
        self.idTienda = idTienda
        self.idProducto = idProducto
        self.stockActual = stockActual
        self.stockMinimo = stockMinimo

class Transaccion:
    def __init__(self, idTransaccion: str, idTienda: str, idEmpleado: str, idProducto: str, cantidad: int, fecha: str):
        self.idTransaccion = idTransaccion
        self.idTienda = idTienda
        self.idEmpleado = idEmpleado
        self.idProducto = idProducto
        self.cantidad = cantidad
        self.fecha = fecha # Consider using datetime objects for dates, currently stored as string

"""Gestor Global del Sistema"""

import uuid
from datetime import datetime

class SistemaCadenaRetail:
    def __init__(self):
        # Atributos Privados
        self.productos = {}      # Key: idProducto, Value: Producto
        self.tiendas = {}          # Key: idTienda, Value: Tienda
        self.inventario = {}       # Key: idTienda + "_" + idProducto, Value: InventarioItem
        self.empleados = []        # List of Empleado objects
        self.transacciones = []    # List of Transaccion objects

    def registrarVenta(self, idTienda: str, idEmpleado: str, idProducto: str, cantidad: int, fecha_str: str) -> bool:
        # 1. Obtener la clave compuesta del inventario
        claveInventario = f"{idTienda}_{idProducto}"
        item = self.inventario.get(claveInventario)

        # 2. Validar existencias
        if item is None or item.stockActual < cantidad:
            print("Error: Stock insuficiente o producto no asignado a la tienda.")
            return False

        # 3. Descontar stock
        item.stockActual -= cantidad

        # 4. Registrar la transacción de forma independiente
        nuevaTransaccion = Transaccion(
            idTransaccion = str(uuid.uuid4()), # GenerarID()
            idTienda = idTienda,
            idEmpleado = idEmpleado,
            idProducto = idProducto,
            cantidad = cantidad,
            fecha = fecha_str
        )
        self.transacciones.append(nuevaTransaccion)

        print(f"Venta de {cantidad} unidades de {idProducto} en tienda {idTienda} registrada exitosamente.")
        return True

    # Métodos auxiliares para añadir datos (para pruebas)
    def add_producto(self, producto):
        self.productos[producto.idProducto] = producto

    def add_tienda(self, tienda):
        self.tiendas[tienda.idTienda] = tienda

    def add_inventario_item(self, item):
        claveInventario = f"{item.idTienda}_{item.idProducto}"
        self.inventario[claveInventario] = item

    def add_empleado(self, empleado):
        self.empleados.append(empleado)

"""DESAFIO N°47

Puntos clave de la solución:

self.libros = []: Inicializa la lista vacía dentro del constructor __init__ para que cada autor tenga su propio historial de libros independiente.

append(titulo): Método estándar de las listas en Python para añadir elementos al final.

Comprobación antes de eliminar: Se usa if titulo in self.libros: antes de aplicar remove(). De lo contrario, intentar borrar un libro que no está en la lista lanzaría un error (ValueError).
"""

class Autor:
    def __init__(self, nombre, nacionalidad):
        self.nombre = nombre
        self.nacionalidad = nacionalidad
        self.libros = []  # Lista inicializada vacía para almacenar los libros

    def agregar_libro(self, titulo):
        """Agrega un libro a la lista del autor."""
        self.libros.append(titulo)
        print(f"Libro '{titulo}' agregado con éxito.")

    def eliminar_libro(self, titulo):
        """Elimina un libro de la lista si existe."""
        if titulo in self.libros:
            self.libros.remove(titulo)
            print(f"Libro '{titulo}' eliminado.")
        else:
            print(f"El libro '{titulo}' no se encuentra en la lista.")

    def mostrar_informacion(self):
        """Muestra los datos del autor y su lista de libros."""
        print(f"\nAutor: {self.nombre} ({self.nacionalidad})")
        if self.libros:
            print("Libros publicados:")
            for libro in self.libros:
                print(f" - {libro}")
        else:
            print("Aún no tiene libros registrados.")


# --- Ejemplo de uso ---

# 1. Crear una instancia de Autor
autor1 = Autor("Gabriel García Márquez", "Colombiano")

# 2. Agregar libros
autor1.agregar_libro("Cien años de soledad")
autor1.agregar_libro("El amor en los tiempos del cólera")

# 3. Mostrar el estado actual
autor1.mostrar_informacion()

# 4. Eliminar un libro
autor1.eliminar_libro("Cien años de soledad")

# 5. Mostrar la información actualizada
autor1.mostrar_informacion()

"""DESAFIO N°48

Para relacionar la clase Libro con la clase Autor, la forma más limpia y orientada a objetos en Python es pasar instancias en lugar de simples cadenas de texto.

Existen dos formas principales de hacerlo según la dirección de la relación:

Opción 1: El Libro contiene a su Autor (Composición / Asociación)
En este enfoque, al crear un Libro, le pasas el objeto Autor completo como uno de sus atributos.
"""

class Autor:
    def __init__(self, nombre, nacionalidad):
        self.nombre = nombre
        self.nacionalidad = nacionalidad

class Libro:
    def __init__(self, titulo, genero, isbn, autor):
        self.titulo = titulo
        self.genero = genero
        self.isbn = isbn
        self.autor = autor  # Recibe un objeto de tipo Autor

    def mostrar_detalle(self):
        print(f"Título: {self.titulo}")
        print(f"Género: {self.genero}")
        print(f"ISBN: {self.isbn}")
        # Accedemos a los atributos del objeto Autor guardado
        print(f"Autor: {self.autor.nombre} ({self.autor.nacionalidad})")


# --- Uso ---
# 1. Creamos primero el autor
autor_garcia = Autor("Gabriel García Márquez", "Colombiano")

# 2. Creamos el libro pasándole el objeto autor
libro1 = Libro("Cien años de soledad", "Realismo mágico", "978-0307474728", autor_garcia)

# 3. Mostramos la información
libro1.mostrar_detalle()

"""Opción 2: Relación bidireccional (Listar Objetos Libro dentro de Autor)
Ampliando el Desafío 47, en lugar de guardar una lista de cadenas con los nombres de los libros, la lista self.libros del Autor almacena las instancias completas de la clase Libro.
"""

class Libro:
    def __init__(self, titulo, genero, isbn):
        self.titulo = titulo
        self.genero = genero
        self.isbn = isbn

class Autor:
    def __init__(self, nombre, nacionalidad):
        self.nombre = nombre
        self.nacionalidad = nacionalidad
        self.libros = []  # Almacenará objetos de la clase Libro

    def agregar_libro(self, libro):
        # Nos aseguramos de que lo que se agrega sea un objeto Libro
        if isinstance(libro, Libro):
            self.libros.append(libro)
            print(f"Libro '{libro.titulo}' agregado a {self.nombre}.")
        else:
            print("El elemento debe ser una instancia de la clase Libro.")

    def mostrar_bibliografia(self):
        print(f"\nLibros de {self.nombre}:")
        for libro in self.libros:
            print(f" - {libro.titulo} [{libro.genero}] (ISBN: {libro.isbn})")


# --- Uso ---
autor_cortazar = Autor("Julio Cortázar", "Argentino")

# Creamos objetos Libro independientes
rayuela = Libro("Rayuela", "Novela", "978-8437604572")
bestiario = Libro("Bestiario", "Cuento", "978-8420424101")

# Agregamos los objetos libro al autor
autor_cortazar.agregar_libro(rayuela)
autor_cortazar.agregar_libro(bestiario)

autor_cortazar.mostrar_bibliografia()

"""DESAFIO N°49: Para representar una biblioteca completa que administre autores y libros, la elección de las estructuras de datos depende de qué operaciones necesites realizar con mayor frecuencia (búsquedas rápidas, listados ordenados o evitar duplicados)."""

class Biblioteca:
    def __init__(self, nombre):
        self.nombre = nombre
        # Estructura principal: Diccionarios para acceso directo
        self.catalogo_libros = {}   # Key: isbn -> Value: objeto Libro
        self.autores = {}           # Key: nombre_autor -> Value: objeto Autor
        self.generos_disponibles = set()  # p. ej. {"Ficción", "Novela", "Historia"}

"""En este caso Diccionarios (dict) — Para búsquedas rápidas $O(1)$Es la mejor opción para almacenar la colección principal. Al usar claves únicas (como el ISBN para libros o el ID/Nombre para autores), puedes consultar o eliminar un elemento al instante sin recorrer toda la lista."""

self.generos_disponibles = set()  # p. ej. {"Ficción", "Novela", "Historia"}

"""Conjuntos (set) — Para evitar duplicados e índices rápidos
Útiles para gestionar géneros literarios o mantener un registro de ISBNs registrados sin permitir duplicados.
"""

class Libro:
    def __init__(self, titulo, genero, isbn):
        self.titulo = titulo
        self.genero = genero
        self.isbn = isbn

class Autor:
    def __init__(self, nombre, nacionalidad):
        self.nombre = nombre
        self.nacionalidad = nacionalidad

class Biblioteca:
    def __init__(self, nombre):
        self.nombre = nombre
        self.libros = {}   # isbn: Libro
        self.autores = {}  # nombre: Autor

    def registrar_autor(self, autor):
        if autor.nombre not in self.autores:
            self.autores[autor.nombre] = autor
            print(f"Autor '{autor.nombre}' registrado.")

    def agregar_libro(self, libro, nombre_autor):
        # Asocia el libro al autor y lo guarda en el catálogo general
        if nombre_autor in self.autores:
            self.libros[libro.isbn] = {
                "libro": libro,
                "autor": self.autores[nombre_autor]
            }
            print(f"Libro '{libro.titulo}' agregado al catálogo.")
        else:
            print(f"Error: Primero debes registrar al autor '{nombre_autor}'.")

    def buscar_por_isbn(self, isbn):
        """Búsqueda directa O(1) usando la clave del diccionario."""
        registro = self.libros.get(isbn)
        if registro:
            libro = registro["libro"]
            autor = registro["autor"]
            print(f"\n[Encontrado] {libro.titulo} - {autor.nombre} ({libro.genero})")
        else:
            print("\nLibro no encontrado.")


# --- Uso del sistema ---
mi_biblioteca = Biblioteca("Biblioteca Central")

# 1. Registrar autor
autor1 = Autor("Gabriel García Márquez", "Colombiano")
mi_biblioteca.registrar_autor(autor1)

# 2. Registrar libro
libro1 = Libro("Cien años de soledad", "Realismo Mágico", "978-0307474728")
mi_biblioteca.agregar_libro(libro1, "Gabriel García Márquez")

# 3. Búsqueda instantánea por ISBN
mi_biblioteca.buscar_por_isbn("978-0307474728")

"""Resumen de estructuras según la necesidad:

dict: Para libros y autores (búsqueda instantánea por ISBN o nombre).

list: Para orden de llegada, rankings o historiales.

set: Para categorías únicas o tags de búsqueda.

DESAFIO N°50: Para mejorar la clase Autor y simular mejor un contexto real o una plataforma editorial/bibliotecaria, se pueden incorporar atributos descriptivos, métricas cuantitativas y métodos de consulta o formato.
"""

from datetime import datetime

class Autor:
    def __init__(self, nombre, apellido, nacionalidad, fecha_nacimiento):
        self.nombre = nombre
        self.apellido = apellido
        self.nacionalidad = nacionalidad
        self.fecha_nacimiento = fecha_nacimiento  # Cadena en formato 'YYYY-MM-DD'
        self.biografia = ""
        self.premios = []
        self.libros = []  # Lista de objetos o diccionarios Libro

    def calcular_edad(self):
        """Calcula la edad actual del autor."""
        fecha_nac = datetime.strptime(self.fecha_nacimiento, "%Y-%m-%d")
        hoy = datetime.now()
        edad = hoy.year - fecha_nac.year - ((hoy.month, hoy.day) < (fecha_nac.month, fecha_nac.day))
        return edad

    def obtener_nombre_bibliografico(self):
        """Retorna el nombre formateado para citas (Ej: 'Cervantes, Miguel de')."""
        return f"{self.apellido.upper()}, {self.nombre}"

    def agregar_premio(self, premio):
        """Registra un premio en la lista sin duplicados."""
        if premio not in self.premios:
            self.premios.append(premio)
            print(f"Premio '{premio}' añadido a {self.nombre}.")

    def agregar_libro(self, libro):
        self.libros.append(libro)

    def total_libros(self):
        return len(self.libros)


# --- Ejemplo de uso ---
autor = Autor("Isabel", "Allende", "Chilena", "1942-08-02")

# Formato y métodos
print(f"Cita bibliográfica: {autor.obtener_nombre_bibliografico()}")
print(f"Edad: {autor.calcular_edad()} años")

autor.agregar_premio("Premio Nacional de Literatura de Chile")
autor.agregar_premio("Medalla de la Libertad")
print(f"Premios: {autor.premios}")

"""Formato de nombre: obtener_nombre_citado() (retorna el nombre en formato bibliográfico: "García Márquez, G.").

Gestión de reconocimientos: agregar_premio(premio).

Filtros de catálogo: obtener_libros_por_genero(genero) o obtener_libro_mas_reciente().

Métricas del autor: promedio_paginas() o total_libros_publicados().

DESAFIO N°51:
Para implementar una función de búsqueda mas eficiente en una biblioteca, la clave está en definir por qué criterio se buscará (título, autor, ISBN o género) y qué tan flexible debe ser la coincidencia (búsqueda exacta vs. parcial/insensible a mayúsculas).
"""

class Libro:
    def __init__(self, titulo, isbn, genero):
        self.titulo = titulo
        self.isbn = isbn
        self.genero = genero

    def __repr__(self):
        return f"'{self.titulo}' (ISBN: {self.isbn})"

class Autor:
    def __init__(self, nombre, nacionalidad):
        self.nombre = nombre
        self.nacionalidad = nacionalidad

    def __repr__(self):
        return f"{self.nombre} ({self.nacionalidad})"


class Biblioteca:
    def __init__(self):
        self.catalogo_libros = []  # Lista de objetos Libro
        self.autores = []          # Lista de objetos Autor

    def buscar_libro(self, criterio):
        """
        Busca libros por título o ISBN (coincidencia parcial e insensible a mayúsculas).
        """
        criterio_norm = criterio.strip().lower()
        resultados = [
            libro for libro in self.catalogo_libros
            if criterio_norm in libro.titulo.lower() or criterio_norm == libro.isbn.lower()
        ]
        return resultados

    def buscar_autor(self, nombre_parcial):
        """
        Busca autores por nombre completo o parcial.
        """
        criterio_norm = nombre_parcial.strip().lower()
        return [
            autor for autor in self.autores
            if criterio_norm in autor.nombre.lower()
        ]


# --- Ejemplo de Uso ---
biblio = Biblioteca()

# Cargar datos de prueba
biblio.autores.extend([
    Autor("Gabriel García Márquez", "Colombiano"),
    Autor("Julio Cortázar", "Argentino")
])

biblio.catalogo_libros.extend([
    Libro("Cien años de soledad", "978-0307474728", "Realismo Mágico"),
    Libro("El coronel no tiene quien le escriba", "978-0307474506", "Novela"),
    Libro("Rayuela", "978-8437604572", "Novela")
])

# 1. Búsqueda de libros por término parcial
print("Búsqueda de libro ('coronel'):", biblio.buscar_libro("coronel"))

# 2. Búsqueda de libros por ISBN exacto
print("Búsqueda por ISBN ('978-8437604572'):", biblio.buscar_libro("978-8437604572"))

# 3. Búsqueda de autor por nombre parcial
print("Búsqueda de autor ('García'):", biblio.buscar_autor("García"))