# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRk2jn3zIVQXwX-Rz70xnCVUJt7WSjFk
"""

def es_primo(numero: int) -> bool:
    """
    Verifica si un número entero es primo.

    Un número primo es aquel mayor que 1 que solo es divisible
    por 1 y por sí mismo.

    Args:
        numero (int): El número a verificar.

    Returns:
        bool: True si el número es primo, False en caso contrario.
    """
    # Los números menores o iguales a 1 no son primos
    if numero <= 1:
        return False

    # El 2 es el único primo par
    if numero == 2:
        return True

    # Si es par y mayor que 2, no es primo
    if numero % 2 == 0:
        return False

    # Verificamos divisores impares desde 3 hasta la raíz cuadrada del número
    # (Optimización matemática: no hace falta buscar más allá de la raíz cuadrada)
    limite = int(numero ** 0.5) + 1
    for i in range(3, limite, 2):
        if numero % i == 0:
            return False # Encontró un divisor, no es primo

    return True


def contar_primos_en_lista(lista_numeros: list) -> int:
    """
    Cuenta cuántos números primos existen en una lista dada.

    Reutiliza la función 'es_primo' para evaluar cada elemento.

    Args:
        lista_numeros (list): Una lista de números enteros.

    Returns:
        int: La cantidad de números primos encontrados en la lista.
    """
    contador = 0
    for numero in lista_numeros:
        if es_primo(numero):
            contador += 1
    return contador


def main():
    """
    Función principal que integra la lógica del desafío.
    Define una lista de prueba, ejecuta las funciones y muestra los resultados.
    """
    print("--- Desafío 32: Verificación y cálculo de números primos --- \n")

    # 1. Lista de prueba con diferentes tipos de números (negativos, ceros, primos y compuestos)
    numeros_prueba = [2, 3, 4, 11, 15, 17, 20, 23, 1, 0, -5, 97]

    print(f"Lista de números a evaluar: {numeros_prueba}")

    # 2. Demostración de la primera función (es_primo) de forma individual
    ejemplo_numero = 17
    if es_primo(ejemplo_numero):
        print(f"Verificación individual: El número {ejemplo_numero} SÍ es primo.")
    else:
        print(f"Verificación individual: El número {ejemplo_numero} NO es primo.")

    # 3. Integración y cálculo de la lista usando la segunda función
    total_primos = contar_primos_en_lista(numeros_prueba)

    # 4. Mostrar resultados finales
    print("\n--- Resultados ---")
    print(f"Cantidad de números primos en la lista: {total_primos}")

    # Extra: Mostrar cuáles son para que el usuario lo verifique visualmente
    primos_encontrados = [num for num in numeros_prueba if es_primo(num)]
    print(f"Los números primos encontrados son: {primos_encontrados}")


# Este condicional asegura que el main solo se ejecute si el archivo se corre directamente
if __name__ == "__main__":
    main()